url to scrap:
  - https://www.seek.co.nz/Firmware-engineer-jobs?sortmode=ListedDate
  - https://www.seek.co.nz/Embedded-engineer-jobs?sortmode=ListedDate
  - https://www.seek.co.nz/Software-engineer-jobs?sortmode=ListedDate